#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TIME_STEP 50
#define UNKNOWN 99999.99
#define GREEN_DETECTION_INTERVAL 5
#define YELLOW_DETECTION_INTERVAL 5
#define RED_DETECTION_INTERVAL 2

#endif /* CONSTANTS_H */